// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// set_seed
void set_seed(unsigned int seed);
RcppExport SEXP _CLEAN_set_seed(SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< unsigned int >::type seed(seedSEXP);
    set_seed(seed);
    return R_NilValue;
END_RCPP
}
// CleanMeanC
Rcpp::List CleanMeanC(arma::mat& ymat, arma::sp_mat& NNmatrix, int nperm, int s);
RcppExport SEXP _CLEAN_CleanMeanC(SEXP ymatSEXP, SEXP NNmatrixSEXP, SEXP npermSEXP, SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type ymat(ymatSEXP);
    Rcpp::traits::input_parameter< arma::sp_mat& >::type NNmatrix(NNmatrixSEXP);
    Rcpp::traits::input_parameter< int >::type nperm(npermSEXP);
    Rcpp::traits::input_parameter< int >::type s(sSEXP);
    rcpp_result_gen = Rcpp::wrap(CleanMeanC(ymat, NNmatrix, nperm, s));
    return rcpp_result_gen;
END_RCPP
}
// CleanDiffC
Rcpp::List CleanDiffC(arma::mat& ymat, arma::sp_mat& NNmatrix, arma::vec group, int nperm, int s);
RcppExport SEXP _CLEAN_CleanDiffC(SEXP ymatSEXP, SEXP NNmatrixSEXP, SEXP groupSEXP, SEXP npermSEXP, SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type ymat(ymatSEXP);
    Rcpp::traits::input_parameter< arma::sp_mat& >::type NNmatrix(NNmatrixSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type group(groupSEXP);
    Rcpp::traits::input_parameter< int >::type nperm(npermSEXP);
    Rcpp::traits::input_parameter< int >::type s(sSEXP);
    rcpp_result_gen = Rcpp::wrap(CleanDiffC(ymat, NNmatrix, group, nperm, s));
    return rcpp_result_gen;
END_RCPP
}
// MassiveMeanC
Rcpp::List MassiveMeanC(arma::mat ymat, int nperm, int s);
RcppExport SEXP _CLEAN_MassiveMeanC(SEXP ymatSEXP, SEXP npermSEXP, SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type ymat(ymatSEXP);
    Rcpp::traits::input_parameter< int >::type nperm(npermSEXP);
    Rcpp::traits::input_parameter< int >::type s(sSEXP);
    rcpp_result_gen = Rcpp::wrap(MassiveMeanC(ymat, nperm, s));
    return rcpp_result_gen;
END_RCPP
}
// MassiveDiffC
Rcpp::List MassiveDiffC(arma::mat ymat, arma::vec group, int nperm, int s);
RcppExport SEXP _CLEAN_MassiveDiffC(SEXP ymatSEXP, SEXP groupSEXP, SEXP npermSEXP, SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type ymat(ymatSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type group(groupSEXP);
    Rcpp::traits::input_parameter< int >::type nperm(npermSEXP);
    Rcpp::traits::input_parameter< int >::type s(sSEXP);
    rcpp_result_gen = Rcpp::wrap(MassiveDiffC(ymat, group, nperm, s));
    return rcpp_result_gen;
END_RCPP
}
// computetraceABA
double computetraceABA(arma::mat A, arma::mat B);
RcppExport SEXP _CLEAN_computetraceABA(SEXP ASEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type A(ASEXP);
    Rcpp::traits::input_parameter< arma::mat >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(computetraceABA(A, B));
    return rcpp_result_gen;
END_RCPP
}
// CovRegOptimC
double CovRegOptimC(double rho, arma::mat& epsilon, arma::mat corMat_base);
RcppExport SEXP _CLEAN_CovRegOptimC(SEXP rhoSEXP, SEXP epsilonSEXP, SEXP corMat_baseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type corMat_base(corMat_baseSEXP);
    rcpp_result_gen = Rcpp::wrap(CovRegOptimC(rho, epsilon, corMat_base));
    return rcpp_result_gen;
END_RCPP
}
// ObtainVarCompsC
Rcpp::List ObtainVarCompsC(double rho, arma::mat& epsilon, arma::mat corMat_base);
RcppExport SEXP _CLEAN_ObtainVarCompsC(SEXP rhoSEXP, SEXP epsilonSEXP, SEXP corMat_baseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type corMat_base(corMat_baseSEXP);
    rcpp_result_gen = Rcpp::wrap(ObtainVarCompsC(rho, epsilon, corMat_base));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_CLEAN_set_seed", (DL_FUNC) &_CLEAN_set_seed, 1},
    {"_CLEAN_CleanMeanC", (DL_FUNC) &_CLEAN_CleanMeanC, 4},
    {"_CLEAN_CleanDiffC", (DL_FUNC) &_CLEAN_CleanDiffC, 5},
    {"_CLEAN_MassiveMeanC", (DL_FUNC) &_CLEAN_MassiveMeanC, 3},
    {"_CLEAN_MassiveDiffC", (DL_FUNC) &_CLEAN_MassiveDiffC, 4},
    {"_CLEAN_computetraceABA", (DL_FUNC) &_CLEAN_computetraceABA, 2},
    {"_CLEAN_CovRegOptimC", (DL_FUNC) &_CLEAN_CovRegOptimC, 3},
    {"_CLEAN_ObtainVarCompsC", (DL_FUNC) &_CLEAN_ObtainVarCompsC, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_CLEAN(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
