// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// set_seed
void set_seed(unsigned int seed);
RcppExport SEXP _CLEAN_set_seed(SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< unsigned int >::type seed(seedSEXP);
    set_seed(seed);
    return R_NilValue;
END_RCPP
}
// CleanMeanC
Rcpp::List CleanMeanC(arma::mat& ymat, arma::sp_mat& NNmatrix, int nperm, int s);
RcppExport SEXP _CLEAN_CleanMeanC(SEXP ymatSEXP, SEXP NNmatrixSEXP, SEXP npermSEXP, SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type ymat(ymatSEXP);
    Rcpp::traits::input_parameter< arma::sp_mat& >::type NNmatrix(NNmatrixSEXP);
    Rcpp::traits::input_parameter< int >::type nperm(npermSEXP);
    Rcpp::traits::input_parameter< int >::type s(sSEXP);
    rcpp_result_gen = Rcpp::wrap(CleanMeanC(ymat, NNmatrix, nperm, s));
    return rcpp_result_gen;
END_RCPP
}
// CleanDiffC
Rcpp::List CleanDiffC(arma::mat& ymat, arma::sp_mat& NNmatrix, arma::vec group, int nperm, int s);
RcppExport SEXP _CLEAN_CleanDiffC(SEXP ymatSEXP, SEXP NNmatrixSEXP, SEXP groupSEXP, SEXP npermSEXP, SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type ymat(ymatSEXP);
    Rcpp::traits::input_parameter< arma::sp_mat& >::type NNmatrix(NNmatrixSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type group(groupSEXP);
    Rcpp::traits::input_parameter< int >::type nperm(npermSEXP);
    Rcpp::traits::input_parameter< int >::type s(sSEXP);
    rcpp_result_gen = Rcpp::wrap(CleanDiffC(ymat, NNmatrix, group, nperm, s));
    return rcpp_result_gen;
END_RCPP
}
// CleanerPermC
Rcpp::List CleanerPermC(arma::mat& xmat, arma::mat& ymat, int nperm, int s);
RcppExport SEXP _CLEAN_CleanerPermC(SEXP xmatSEXP, SEXP ymatSEXP, SEXP npermSEXP, SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type xmat(xmatSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type ymat(ymatSEXP);
    Rcpp::traits::input_parameter< int >::type nperm(npermSEXP);
    Rcpp::traits::input_parameter< int >::type s(sSEXP);
    rcpp_result_gen = Rcpp::wrap(CleanerPermC(xmat, ymat, nperm, s));
    return rcpp_result_gen;
END_RCPP
}
// CleanerExpandPermC
Rcpp::List CleanerExpandPermC(arma::vec U, arma::mat& permU, arma::sp_mat& NNmatrix);
RcppExport SEXP _CLEAN_CleanerExpandPermC(SEXP USEXP, SEXP permUSEXP, SEXP NNmatrixSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type U(USEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type permU(permUSEXP);
    Rcpp::traits::input_parameter< arma::sp_mat& >::type NNmatrix(NNmatrixSEXP);
    rcpp_result_gen = Rcpp::wrap(CleanerExpandPermC(U, permU, NNmatrix));
    return rcpp_result_gen;
END_RCPP
}
// computetraceABA
double computetraceABA(arma::mat A, arma::mat B);
RcppExport SEXP _CLEAN_computetraceABA(SEXP ASEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type A(ASEXP);
    Rcpp::traits::input_parameter< arma::mat >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(computetraceABA(A, B));
    return rcpp_result_gen;
END_RCPP
}
// CovRegOptimC
double CovRegOptimC(double rho, arma::mat& epsilon, arma::mat corMat_base);
RcppExport SEXP _CLEAN_CovRegOptimC(SEXP rhoSEXP, SEXP epsilonSEXP, SEXP corMat_baseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type corMat_base(corMat_baseSEXP);
    rcpp_result_gen = Rcpp::wrap(CovRegOptimC(rho, epsilon, corMat_base));
    return rcpp_result_gen;
END_RCPP
}
// ObtainVarCompsC
Rcpp::List ObtainVarCompsC(double rho, arma::mat& epsilon, arma::mat corMat_base);
RcppExport SEXP _CLEAN_ObtainVarCompsC(SEXP rhoSEXP, SEXP epsilonSEXP, SEXP corMat_baseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type corMat_base(corMat_baseSEXP);
    rcpp_result_gen = Rcpp::wrap(ObtainVarCompsC(rho, epsilon, corMat_base));
    return rcpp_result_gen;
END_RCPP
}
// CleanVarC
Rcpp::List CleanVarC(arma::mat& ymat, arma::sp_mat& NNmatrix, arma::sp_mat& Kmatrix, int nperm, int s);
RcppExport SEXP _CLEAN_CleanVarC(SEXP ymatSEXP, SEXP NNmatrixSEXP, SEXP KmatrixSEXP, SEXP npermSEXP, SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type ymat(ymatSEXP);
    Rcpp::traits::input_parameter< arma::sp_mat& >::type NNmatrix(NNmatrixSEXP);
    Rcpp::traits::input_parameter< arma::sp_mat& >::type Kmatrix(KmatrixSEXP);
    Rcpp::traits::input_parameter< int >::type nperm(npermSEXP);
    Rcpp::traits::input_parameter< int >::type s(sSEXP);
    rcpp_result_gen = Rcpp::wrap(CleanVarC(ymat, NNmatrix, Kmatrix, nperm, s));
    return rcpp_result_gen;
END_RCPP
}
// Ciderperm
Rcpp::List Ciderperm(arma::mat& ymat, arma::mat& xmat, arma::sp_mat& NNmatrix, int nperm, int s);
RcppExport SEXP _CLEAN_Ciderperm(SEXP ymatSEXP, SEXP xmatSEXP, SEXP NNmatrixSEXP, SEXP npermSEXP, SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type ymat(ymatSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type xmat(xmatSEXP);
    Rcpp::traits::input_parameter< arma::sp_mat& >::type NNmatrix(NNmatrixSEXP);
    Rcpp::traits::input_parameter< int >::type nperm(npermSEXP);
    Rcpp::traits::input_parameter< int >::type s(sSEXP);
    rcpp_result_gen = Rcpp::wrap(Ciderperm(ymat, xmat, NNmatrix, nperm, s));
    return rcpp_result_gen;
END_RCPP
}
// CovRegOptim2C
double CovRegOptim2C(NumericVector phi, const arma::mat& epsilon, const arma::sp_mat& corMat_base1, const arma::sp_mat& corMat_base2);
RcppExport SEXP _CLEAN_CovRegOptim2C(SEXP phiSEXP, SEXP epsilonSEXP, SEXP corMat_base1SEXP, SEXP corMat_base2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type corMat_base1(corMat_base1SEXP);
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type corMat_base2(corMat_base2SEXP);
    rcpp_result_gen = Rcpp::wrap(CovRegOptim2C(phi, epsilon, corMat_base1, corMat_base2));
    return rcpp_result_gen;
END_RCPP
}
// MeanVarWithin
arma::mat MeanVarWithin(const arma::mat& m, const arma::sp_mat& NNmatrix);
RcppExport SEXP _CLEAN_MeanVarWithin(SEXP mSEXP, SEXP NNmatrixSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type m(mSEXP);
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type NNmatrix(NNmatrixSEXP);
    rcpp_result_gen = Rcpp::wrap(MeanVarWithin(m, NNmatrix));
    return rcpp_result_gen;
END_RCPP
}
// adjust_local_variance
arma::mat adjust_local_variance(const arma::mat& m1, const arma::mat& m2, const arma::sp_mat& NNmatrix);
RcppExport SEXP _CLEAN_adjust_local_variance(SEXP m1SEXP, SEXP m2SEXP, SEXP NNmatrixSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type m1(m1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type m2(m2SEXP);
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type NNmatrix(NNmatrixSEXP);
    rcpp_result_gen = Rcpp::wrap(adjust_local_variance(m1, m2, NNmatrix));
    return rcpp_result_gen;
END_RCPP
}
// adjust_data_local_sd
arma::mat adjust_data_local_sd(const arma::mat& m1, const arma::sp_mat& NNmatrix);
RcppExport SEXP _CLEAN_adjust_data_local_sd(SEXP m1SEXP, SEXP NNmatrixSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type m1(m1SEXP);
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type NNmatrix(NNmatrixSEXP);
    rcpp_result_gen = Rcpp::wrap(adjust_data_local_sd(m1, NNmatrix));
    return rcpp_result_gen;
END_RCPP
}
// adjust_data_local_sd_both
arma::mat adjust_data_local_sd_both(const arma::mat& m1, const arma::sp_mat& NNmatrix);
RcppExport SEXP _CLEAN_adjust_data_local_sd_both(SEXP m1SEXP, SEXP NNmatrixSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type m1(m1SEXP);
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type NNmatrix(NNmatrixSEXP);
    rcpp_result_gen = Rcpp::wrap(adjust_data_local_sd_both(m1, NNmatrix));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_CLEAN_set_seed", (DL_FUNC) &_CLEAN_set_seed, 1},
    {"_CLEAN_CleanMeanC", (DL_FUNC) &_CLEAN_CleanMeanC, 4},
    {"_CLEAN_CleanDiffC", (DL_FUNC) &_CLEAN_CleanDiffC, 5},
    {"_CLEAN_CleanerPermC", (DL_FUNC) &_CLEAN_CleanerPermC, 4},
    {"_CLEAN_CleanerExpandPermC", (DL_FUNC) &_CLEAN_CleanerExpandPermC, 3},
    {"_CLEAN_computetraceABA", (DL_FUNC) &_CLEAN_computetraceABA, 2},
    {"_CLEAN_CovRegOptimC", (DL_FUNC) &_CLEAN_CovRegOptimC, 3},
    {"_CLEAN_ObtainVarCompsC", (DL_FUNC) &_CLEAN_ObtainVarCompsC, 3},
    {"_CLEAN_CleanVarC", (DL_FUNC) &_CLEAN_CleanVarC, 5},
    {"_CLEAN_Ciderperm", (DL_FUNC) &_CLEAN_Ciderperm, 5},
    {"_CLEAN_CovRegOptim2C", (DL_FUNC) &_CLEAN_CovRegOptim2C, 4},
    {"_CLEAN_MeanVarWithin", (DL_FUNC) &_CLEAN_MeanVarWithin, 2},
    {"_CLEAN_adjust_local_variance", (DL_FUNC) &_CLEAN_adjust_local_variance, 3},
    {"_CLEAN_adjust_data_local_sd", (DL_FUNC) &_CLEAN_adjust_data_local_sd, 2},
    {"_CLEAN_adjust_data_local_sd_both", (DL_FUNC) &_CLEAN_adjust_data_local_sd_both, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_CLEAN(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
