# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

set_seed <- function(seed) {
    invisible(.Call('_CLEAN_set_seed', PACKAGE = 'CLEAN', seed))
}

CleanMeanC <- function(ymat, NNmatrix, nperm, s) {
    .Call('_CLEAN_CleanMeanC', PACKAGE = 'CLEAN', ymat, NNmatrix, nperm, s)
}

CleanDiffC <- function(ymat, NNmatrix, group, nperm, s) {
    .Call('_CLEAN_CleanDiffC', PACKAGE = 'CLEAN', ymat, NNmatrix, group, nperm, s)
}

CleanerPermC <- function(xmat, ymat, nperm, s) {
    .Call('_CLEAN_CleanerPermC', PACKAGE = 'CLEAN', xmat, ymat, nperm, s)
}

CleanerExpandPermC <- function(U, permU, NNmatrix) {
    .Call('_CLEAN_CleanerExpandPermC', PACKAGE = 'CLEAN', U, permU, NNmatrix)
}

MassiveMeanC <- function(ymat, nperm, s) {
    .Call('_CLEAN_MassiveMeanC', PACKAGE = 'CLEAN', ymat, nperm, s)
}

MassiveDiffC <- function(ymat, group, nperm, s) {
    .Call('_CLEAN_MassiveDiffC', PACKAGE = 'CLEAN', ymat, group, nperm, s)
}

computetraceABA <- function(A, B) {
    .Call('_CLEAN_computetraceABA', PACKAGE = 'CLEAN', A, B)
}

CovRegOptimC <- function(rho, epsilon, corMat_base) {
    .Call('_CLEAN_CovRegOptimC', PACKAGE = 'CLEAN', rho, epsilon, corMat_base)
}

ObtainVarCompsC <- function(rho, epsilon, corMat_base) {
    .Call('_CLEAN_ObtainVarCompsC', PACKAGE = 'CLEAN', rho, epsilon, corMat_base)
}

