# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

set_seed <- function(seed) {
    invisible(.Call('_CLEAN_set_seed', PACKAGE = 'CLEAN', seed))
}

CleanMeanC <- function(ymat, NNmatrix, nperm, s) {
    .Call('_CLEAN_CleanMeanC', PACKAGE = 'CLEAN', ymat, NNmatrix, nperm, s)
}

CleanDiffC <- function(ymat, NNmatrix, group, nperm, s) {
    .Call('_CLEAN_CleanDiffC', PACKAGE = 'CLEAN', ymat, NNmatrix, group, nperm, s)
}

CleanerPermC <- function(xmat, ymat, nperm, s) {
    .Call('_CLEAN_CleanerPermC', PACKAGE = 'CLEAN', xmat, ymat, nperm, s)
}

CleanerExpandPermC <- function(U, permU, NNmatrix) {
    .Call('_CLEAN_CleanerExpandPermC', PACKAGE = 'CLEAN', U, permU, NNmatrix)
}

computetraceABA <- function(A, B) {
    .Call('_CLEAN_computetraceABA', PACKAGE = 'CLEAN', A, B)
}

CovRegOptimC <- function(rho, epsilon, corMat_base) {
    .Call('_CLEAN_CovRegOptimC', PACKAGE = 'CLEAN', rho, epsilon, corMat_base)
}

ObtainVarCompsC <- function(rho, epsilon, corMat_base) {
    .Call('_CLEAN_ObtainVarCompsC', PACKAGE = 'CLEAN', rho, epsilon, corMat_base)
}

CleanVarC <- function(ymat, NNmatrix, Kmatrix, nperm, s) {
    .Call('_CLEAN_CleanVarC', PACKAGE = 'CLEAN', ymat, NNmatrix, Kmatrix, nperm, s)
}

Ciderperm <- function(ymat, xmat, NNmatrix, nperm, s) {
    .Call('_CLEAN_Ciderperm', PACKAGE = 'CLEAN', ymat, xmat, NNmatrix, nperm, s)
}

CovRegOptim2C <- function(phi, epsilon, corMat_base1, corMat_base2) {
    .Call('_CLEAN_CovRegOptim2C', PACKAGE = 'CLEAN', phi, epsilon, corMat_base1, corMat_base2)
}

MeanVarWithin <- function(m, NNmatrix) {
    .Call('_CLEAN_MeanVarWithin', PACKAGE = 'CLEAN', m, NNmatrix)
}

adjust_local_variance <- function(m1, m2, NNmatrix) {
    .Call('_CLEAN_adjust_local_variance', PACKAGE = 'CLEAN', m1, m2, NNmatrix)
}

adjust_data_local_sd <- function(m1, NNmatrix) {
    .Call('_CLEAN_adjust_data_local_sd', PACKAGE = 'CLEAN', m1, NNmatrix)
}

